import "./globals.css";

//import components
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";


//theme provider
import { ThemeProvider } from "@/components/theme/ThemeProvider";

//font update
import { Sen } from "next/font/google";

const SenFont = Sen({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700"],
  display: "swap",
})

export const metadata = {
  title: "ELEMENT X TRADE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={SenFont.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
